#!/usr/bin/perl
use strict;
use warnings;

print "Content-type: text/html\n\n";

print <<"HTML";
<!DOCTYPE html>
<html>
<head><title>Perl CGI Echo</title></head>
<body>
<h1>Hello from Perl CGI</h1>
<p>This page was generated by a Perl CGI script.</p>
</body>
</html>
HTML
