#!/usr/bin/perl
use strict;
use warnings;
use CGI qw(:standard);
use CGI::Session;

my $cgi = CGI->new;
my $session = CGI::Session->new(undef, $cgi, {Directory=>'/tmp'});
$session->delete;
$session->flush;

print $cgi->header();
print <<HTML;
<html>
<head><title>Perl Session Destroyed</title></head>
<body>
  <h1>Session Destroyed</h1>
  <a href="/perl-cgiform.html">Back to Perl CGI Form</a>
</body>
</html>
HTML
